export const GRADOVI = ["Aleksinac",
    "Apatin",
    "Aranđelovac",
    "Bajina Bašta",
    "Bačka Palanka",
    "Bačka Topola",
    "Batajnica",
    "Beograd",
    "Beočin",
    "Bečej",
    "Bogatić",
    "Bor",
    "Brus",
    "Bujanovac",
    "Valjevo",
    "Velika Plana",
    "Vladičin Han",
    "Vlasotince",
    "Vranje",
    "Vrbas",
    "Vrnjaćka Banja",
    "Vršac",
    "Vučitrn",
    "Gornji Milanovac",
    "Gračanica",
    "Gnjilane",
    "Dimitrovgrad",
    "Donji Milanovac",
    "Đakovica",
    "Žabalj",
    "Zaječar",
    "Zvečan",
    "Zlatibor",
    "Zrenjanin",
    "Ivanjica",
    "Inđija",
    "Irig",
    "Jagodina",
    "Kikinda",
    "Kladovo",
    "Knjaževac",
    "Kovin",
    "Kosovska Mitrovica",
    "Kostolac",
    "Kragujevac",
    "Kraljevo",
    "Krupanj",
    "Kruševac",
    "Kula",
    "Kuršumlija",
    "Lazarevac",
    "Lebane",
    "Leposavić",
    "Leskovac",
    "Loznica",
    "Ljig",
    "Majdanpek",
    "Mali Zvornik",
    "Mladenovac",
    "Mol",
    "Negotin",
    "Niš",
    "Nova Varoš",
    "Novi Bečej",
    "Novi Kneževac",
    "Novi Pazar",
    "Novi Sad",
    "Obrenovac",
    "Odžaci",
    "Pančevo",
    "Paraćin",
    "Petrovaradin",
    "Petrovac",
    "Peć",
    "Pirot",
    "Podujevo",
    "Požarevac",
    "Požega",
    "Priboj",
    "Prijepolje",
    "Priština",
    "Prizren",
    "Prokuplje",
    "Raška",
    "Ruma",
    "Svilajnac",
    "Svrljig",
    "Sevojno",
    "Senta",
    "Sjenica",
    "Smederevo",
    "Smederevska Palanka",
    "Sokobanja",
    "Sombor",
    "Sopot",
    "Srbobran",
    "Sremska Kamenica",
    "Sremska Mitrovica",
    "Sremski Karlovci",
    "Stara Pazova",
    "Subotica",
    "Surdulica",
    "Surčin",
    "Temerin",
    "Trstenik",
    "Tutin",
    "Ćuprija",
    "Ub",
    "Užice",
    "Uroševac",
    "Futog",
    "Crvenka",
    "Čajetina",
    "Čačak",
    "Šabac",
    "Šid"];

    export const DIJASPORA = ["Austrija",
        "Belgija",
        "Belorusija",
        "BiH",
        "Bugarska",
        "Grčka",
        "Danska",
        "Izrael",
        "Irska",
        "Italija",
        "Jermenija",
        "Kazahstan",
        "Kanada",
        "Kipar",
        "Mađarska",
        "Makedonija",
        "Malta",
        "Nemačka",
        "Norveška",
        "Poljska",
        "Portugal",
        "Rumunija",
        "Rusija",
        "SAD",
        "Slovačka",
        "Slovenija",
        "Turska",
        "UAE",
        "UK",
        "Ukrajina",
        "Finska",
        "Francuska",
        "Holandija",
        "Hrvatska",
        "Crna Gora",
        "Češka",
        "Švajcarska",
        "Švedska",
        "Španija"];